# FEEL FREE TO MODIFY

READ_SPEED = 30 # Characters per second
MIN_IDLE_READ_TIME_MS = 0
MAX_IDLE_READ_TIME_MS = 1000

WRITE_SPEED = 5 # Characters per second
MIN_IDLE_WRITE_TIME_MS = 2000
MAX_IDLE_WRITE_TIME_MS = 7000

# TO BE MODIFIED BY CONSOLE LINE ARGUMENT
SPEED_UP_FACTOR = 1.0   # --speedup
OFFLINE = True          # --offline

# DO NOT MODIFY
S_TO_MS = 10**3
